SELECT
    USER_ID,
    NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1,' ', STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTRING(TLNO, 1,3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER A
ON A.USER_ID = B.WRITER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(BOARD_ID) >= 3
ORDER BY
    1 DESC