SELECT 
    F.PRODUCT_ID,
    F.PRODUCT_NAME,
    F.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM 
    FOOD_PRODUCT F INNER JOIN FOOD_ORDER O
ON
    F.PRODUCT_ID = O.PRODUCT_ID
WHERE 
    YEAR(O.PRODUCE_DATE) = '2022' AND MONTH(O.PRODUCE_DATE) = '05'
GROUP BY
    O.PRODUCT_ID
ORDER BY 
    TOTAL_SALES DESC,
    F.PRODUCT_ID;