SELECT
    A.USER_ID,
    A.NICKNAME,
    SUM(PRICE) AS TOTAL_PRICE
FROM USED_GOODS_USER A 
    JOIN USED_GOODS_BOARD B ON A.USER_ID = B.WRITER_ID
WHERE B.STATUS = 'DONE'
GROUP BY (A.USER_ID)
HAVING SUM(PRICE) >= 700000
ORDER BY 3