SELECT
    MCDP_CD AS '진료과코드',
    COUNT(*) AS '5월예약건수'
FROM (
    SELECT 
        MCDP_CD
     FROM 
        APPOINTMENT
    WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 5
) AS SUB
GROUP BY
    MCDP_CD
ORDER BY 2, 1;