SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
WHERE EXISTS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE A.CAR_ID = B.CAR_ID AND MONTH(B.START_DATE) = 10
) AND CAR_TYPE = '세단'
ORDER BY 1 DESC