SELECT
    INFO.INGREDIENT_TYPE,
    SUM(HALF.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    ICECREAM_INFO INFO, FIRST_HALF HALF
WHERE 
    HALF.FLAVOR = INFO.FLAVOR
GROUP BY
    INFO.INGREDIENT_TYPE
ORDER BY
    2;